[package]
name = "egui-scrubber"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Simple scrubber for egui for use in video or replay scrubbing"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.29.1"